---
apiVersion: batch/v1
kind: Job
metadata:
  name: clin-fhir-postgres-qa-server-db-transfer
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1200
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: ferlabcrsj/postgres-backup:9bb43092f76e95f17cd09f03a27c65d84112a3cd
        name: clin-fhir-postgres-qa-server-db-transfer
        env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-qa-clin-fhir-credentials
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-qa-clin-fhir-credentials
                key: password
        envFrom:
          - secretRef:
              name: clin-fhir-s3-credentials
          - configMapRef:
              name: clin-fhir-server-s3-backups
          - configMapRef:
              name: clin-fhir-server-db-connection
          - configMapRef:
              name: clin-fhir-server-db-connection-tls
        command:
          - python3
          - /opt/restore.py
        volumeMounts:
          - name: ca-certificate
            mountPath: /opt/ca
            readOnly: true
      volumes:
        - name: ca-certificate
          secret:
            secretName: postgres-qa-ca-certificate
            defaultMode: 0555