---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.git-autosync: "semver:~1"
spec:
  selector:
    matchLabels:
      name: git-autosync
  template:
    metadata:
      labels:
        name: git-autosync
    spec:
      imagePullSecrets:
        - name: images-pull
      containers:
        - name: git-autosync
          image: ferlabcrsj/git-autosync:10d22c3cab424f19ba9ffc2287aa96170195b27a
          env:
            - name: SCRAPE_INTERVAL
              value: "120000"
            - name: LISTING_PATH
              value: "/etc/git-autosync/listing.json"
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.50"
            requests:
              memory: "64Mi"
              cpu: "0.25"
          volumeMounts:
            - name: clin-keycloak-theme
              mountPath: /opt/clin-keycloak-theme
            - name: git-autosync-listing
              mountPath: /etc/git-autosync
      terminationGracePeriodSeconds: 10
      volumes:
        - name: clin-keycloak-theme
          hostPath:
            path: /opt/clin-qa/keycloak-theme
            type: DirectoryOrCreate
        - name: git-autosync-listing
          configMap:
            name: git-autosync-listing