---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
  namespace: clin-dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:6dd3845
        name: clin-fhir-server
