---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clin-fhir-server-backups-prune
spec:
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      backoffLimit: 2
      template:
        spec:
          imagePullSecrets:
            - name: images-pull
          restartPolicy: Never
          containers:
            - image: ferlabcrsj/postgres-backup:b3b4afc0e380db2b2410875208264b59f39a5eff
              name: clin-fhir-server-backups-prune
              command:
                - python3
                - /opt/prune-backups.py
              envFrom:
                - secretRef:
                    name: clin-fhir-s3-credentials
                - configMapRef:
                    name: clin-fhir-server-s3-backups