---
apiVersion: batch/v1
kind: Job
metadata:
  name: enriched-elasticsearch-etl
spec:
  template:
    spec:
      serviceAccountName: spark
      containers:
        - name: enriched-elasticsearch-etl
          image: ferlabcrsj/spark:0edb597e24b5320a3363e0c07050736c325082b5
          env:
            - name: SPARK_CLASS
              value: bio.ferlab.clin.etl.es.Indexer
            - name: SPARK_JAR
              value: s3a://clin-qa-app-datalake/spark/clin-variant-etl.jar
            - name: SPARK_CLIENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spark-defaults
              mountPath: /opt/spark-configs/defaults
              readOnly: true
            - name: enriched-elasticsearch-etl
              mountPath: /opt/spark-configs/enriched-elasticsearch-etl
              readOnly: true
            - name: s3-credentials
              mountPath: /opt/spark-configs/s3-credentials
              readOnly: true
          command:
            - "/opt/client-entrypoint.sh"
          args:
            - http://0.0.0.0:9200
            - variant_index
            - RE_00000
            - variant_centric_template.json
            - variants
            - BAT0
            - config/qa.conf
      restartPolicy: Never
      volumes:
        - name: spark-defaults
          configMap:
            name: spark-defaults
        - name: enriched-elasticsearch-etl
          configMap:
            name: enriched-elasticsearch-etl
        - name: s3-credentials
          secret:
            secretName: s3-credentials
  backoffLimit: 4