---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: airflow-on-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: airflow-on-k8s
  name: airflow-cluster-admin
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
#  - apiGroups: ["batch", "extensions", "apps"]
#    resources: ["jobs"]
#    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow
  namespace: airflow-on-k8s
subjects:
  - kind: ServiceAccount
    name: airflow # Matches ServiceAccount name
    namespace: airflow-on-k8s
roleRef:
  kind: ClusterRole
  name: airflow-cluster-admin # Matches ClusterRole name
  apiGroup: rbac.authorization.k8s.io