apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  # sql_alchemy_conn => base64( postgresql+psycopg2://root:root@postgres-airflow:5432/airflow )
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Jvb3Q6cm9vdEBwb3N0Z3Jlcy1haXJmbG93OjU0MzIvYWlyZmxvdwo=