---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  labels:
    name: spark
data:
  spark-defaults.conf: |
    spark.master=k8s://https://kubernetes.default.svc.cluster.clin.qa
    spark.submit.deployMode=cluster
    spark.kubernetes.namespace=clin-qa
    spark.kubernetes.authenticate.driver.serviceAccountName=spark
    spark.hadoop.fs.s3a.endpoint=https://s3.ops.cqdg.ferlab.bio
    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.fast.upload=true
    spark.hadoop.fs.s3a.connection.ssl.enabled=true
    spark.hadoop.fs.s3a.path.style.access=true
    spark.hadoop.hive.metastore.uris=thrift://hive-metastore:9083
    spark.sql.warehouse.dir=s3a://clin-qa-app-datalake/hive