---
apiVersion: v1
kind: ConfigMap
metadata:
  name: normalized-enriched-etl
  labels:
    name: spark
data:
  spark-ceph.conf: |
    spark.app.name=normalized-enriched-etl
    spark.executor.instances=10
    spark.kubernetes.container.image=ferlabcrsj/spark:0edb597e24b5320a3363e0c07050736c325082b5
    spark.sql.shuffle.partitions=500
    spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.executor.memory=8g
