---
apiVersion: batch/v1
kind: Job
metadata:
  name: normalized-enriched-etl
spec:
  template:
    spec:
      serviceAccountName: spark
      containers:
        - name: normalized-enriched-etl
          image: ferlabcrsj/spark:0edb597e24b5320a3363e0c07050736c325082b5
          env:
            - name: SPARK_CLASS
              value: bio.ferlab.clin.etl.enriched.RunEnriched
            - name: SPARK_JAR
              value: s3a://clin-qa-app-datalake/spark/clin-variant-etl.jar
            - name: SPARK_CLIENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spark-defaults
              mountPath: /opt/spark-configs/defaults
              readOnly: true
            - name: normalized-enriched-etl
              mountPath: /opt/spark-configs/normalized-enriched-etl
              readOnly: true
            - name: s3-credentials
              mountPath: /opt/spark-configs/s3-credentials
              readOnly: true
          command:
            - "/opt/client-entrypoint.sh"
          args:
            - config/qa.conf
            - 201106_A00516_0169_AHFM3HDSXY
            - all
      restartPolicy: Never
      volumes:
        - name: spark-defaults
          configMap:
            name: spark-defaults
        - name: normalized-enriched-etl
          configMap:
            name: normalized-enriched-etl
        - name: s3-credentials
          secret:
            secretName: s3-credentials
  backoffLimit: 4