---
apiVersion: batch/v1
kind: Job
metadata:
  name: hpo-etl-indexer
spec:
  template:
    spec:
      serviceAccountName: spark
      containers:
      - name: hpo-etl-indexer
        image: ferlabcrsj/spark:0edb597e24b5320a3363e0c07050736c325082b5
        env:
          - name: SPARK_CLASS
            value: bio.ferlab.clin.idx.hpo.HPO
          - name: SPARK_JAR
            value: s3a://clin-qa-app-datalake/spark/clin-hpo-etl.jar
          - name: SPARK_CLIENT_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: spark-defaults
            mountPath: /opt/spark-configs/defaults
            readOnly: true
          - name: hpo-etl-indexer
            mountPath: /opt/spark-configs/hpo-obo-parser
            readOnly: true
          - name: s3-credentials
            mountPath: /opt/spark-configs/s3-credentials
            readOnly: true
        command:
          - "/opt/client-entrypoint.sh"
        args:
          - s3a://clin-qa-app-datalake/public/hpo
          - hpo
          - "20210819_v1"
          - s3a://clin-qa-app-datalake/jobs/templates/hpo.json
      restartPolicy: Never
      volumes:
        - name: spark-defaults
          configMap:
            name: spark-defaults
        - name: hpo-etl-indexer
          configMap:
            name: hpo-etl-indexer
        - name: s3-credentials
          secret:
            secretName: s3-credentials
  backoffLimit: 4