---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../common/fhir-server

patchesStrategicMerge:
  - configmaps.yml
  - deployments.yml

commonLabels:
  group: clin-fhir-server
