---
apiVersion: batch/v1
kind: Job
metadata:
  name: genes-tables-to-ndjson
  namespace: spark
spec:
  template:
    spec:
      serviceAccountName: spark
      imagePullSecrets:
        - name: images-pull
      containers:
      - name: genes-tables-to-ndjson
        image: ferlabcrsj/spark:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
        env:
          - name: SPARK_CLASS
            value: bio.ferlab.clin.etl.es.PrepareGeneIndex
          - name: SPARK_JAR
            value: s3a://spark/clin-etl-variant.jar
          - name: SPARK_CLIENT_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: spark-defaults
            mountPath: /opt/spark-configs/defaults
            readOnly: true
          - name: genes-tables-to-ndjson
            mountPath: /opt/spark-configs/genes-tables-to-ndjson
            readOnly: true
          - name: s3-credentials
            mountPath: /opt/spark-configs/s3-credentials
            readOnly: true
        command:
          - "/opt/client-entrypoint.sh"
        args:
          - s3a://clin/es_genes_index_ndjson
      restartPolicy: Never
      volumes:
        - name: spark-defaults
          configMap:
            name: spark-defaults
        - name: genes-tables-to-ndjson
          configMap:
            name: genes-tables-to-ndjson
        - name: s3-credentials
          secret:
            secretName: s3-credentials
  backoffLimit: 4
