---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: 'true'
  name: clin-frontend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      containers:
        - image: ferlabcrsj/clin-frontend:99bbcad197bd913e2b5f0e8c0f23e27ca593382f
          name: clin-frontend
          env:
            - name: PATIENT_SERVICE_URL
              value: https://patient.qa.clin.ferlab.bio/patient
            - name: VARIANT_SERVICE_URL
              value: https://variant.qa.clin.ferlab.bio/variant
            - name: GENE_SERVICE_URL
              value: https://gene.qa.clin.ferlab.bio/gene
            - name: META_SERVICE_URL
              value: https://meta.qa.clin.ferlab.bio/meta
            - name: FHIR_SERVICE_URL
              value: https://fhir.qa.clin.ferlab.bio/fhir
            - name: HPO_SERVICE_URL
              value: https://hpo.qa.clin.ferlab.bio/hpo
            - name: KEYCLOAK_CONFIG
              value: "{\\\"realm\\\": \\\"clin\\\", \\\"url\\\": \\\"https://auth.qa.cqdg.ferlab.bio/auth/\\\", \\\"clientId\\\": \\\"clin-client\\\", \\\"authClientId\\\": \\\"clin-acl\\\"}"