---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: ferlabcrsj/git-autosync:1.2.0
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-ferload
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-ferload
      containers:
      - image: ferlabcrsj/ferload:ecc648f
        name: clin-ferload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-console
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-console
      containers:
      - image: ferlabcrsj/fhir-console:0c2fea2
        name: clin-fhir-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:1.1.0
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:a3b3fbfe4718ce83b560d44b23ab7a3f10d68bf2
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:2.1.6
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:2.1.6
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:323e88e4a6939e443a2e05f5b4f5e7af0a9e1035
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:2.1.6
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:323e88e4a6939e443a2e05f5b4f5e7af0a9e1035
        name: clin-proxy-api-variant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: ferlabcrsj/hive-metastore:652b9944cbab17db5ba45d6ed53735ba191adba1
        name: hive-metastore
