---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:8d7fa33
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:d35d704c458febd073f040e12759b257a7dcd7fd
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:f6c98e8c33c04d3e87fc092232228f5a7a3e94a0
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:f6c98e8c33c04d3e87fc092232228f5a7a3e94a0
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:f6c98e8c33c04d3e87fc092232228f5a7a3e94a0
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:f6c98e8c33c04d3e87fc092232228f5a7a3e94a0
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:f6c98e8c33c04d3e87fc092232228f5a7a3e94a0
        name: clin-proxy-api-variant
