---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:fb8c3f4
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:a8cff7ccf17daea261572a4200965be5a1a46683
        name: clin-frontend
