---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-ferload
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-ferload
      containers:
      - image: ferlabcrsj/ferload:1.0.0
        name: clin-ferload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-console
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-console
      containers:
      - image: ferlabcrsj/fhir-console:1.0.0
        name: clin-fhir-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:c769d64
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:7154cfd61bc1f0a51793f981d5d716c3b74e237c
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:a92864305f3bfe96c28ba907033897a5f993c9a6
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:a92864305f3bfe96c28ba907033897a5f993c9a6
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:a92864305f3bfe96c28ba907033897a5f993c9a6
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:a92864305f3bfe96c28ba907033897a5f993c9a6
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:a92864305f3bfe96c28ba907033897a5f993c9a6
        name: clin-proxy-api-variant
