---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: ferlabcrsj/git-autosync:1.2.0
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-ferload
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-ferload
      containers:
      - image: ferlabcrsj/ferload:d8f1204
        name: clin-ferload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-console
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-console
      containers:
      - image: ferlabcrsj/fhir-console:0c2fea2
        name: clin-fhir-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:1.1.1
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:6bfd2dfea700a8a5dd43a542636dfb30b920b7a8
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:df60e0edaf9c603a95b33dd2798d32e671bd4e63
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:df60e0edaf9c603a95b33dd2798d32e671bd4e63
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:df60e0edaf9c603a95b33dd2798d32e671bd4e63
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:df60e0edaf9c603a95b33dd2798d32e671bd4e63
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:df60e0edaf9c603a95b33dd2798d32e671bd4e63
        name: clin-proxy-api-variant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: clin-qa
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: ferlabcrsj/hive-metastore:652b9944cbab17db5ba45d6ed53735ba191adba1
        name: hive-metastore
