---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:1936359
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:81449f0bfda75eb9ba3178b12e1807488885e619
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:5421137cefa784ba19344c04b335e3ec56baadb8
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:5421137cefa784ba19344c04b335e3ec56baadb8
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:5421137cefa784ba19344c04b335e3ec56baadb8
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:5421137cefa784ba19344c04b335e3ec56baadb8
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:5421137cefa784ba19344c04b335e3ec56baadb8
        name: clin-proxy-api-variant
