---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:c2e8b1d
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:2aaf4892dc7bd9be904eac9f87beda3bfa67133d
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:c40f6edf537c97fe22ac3e0a792c515208a2c044
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:c40f6edf537c97fe22ac3e0a792c515208a2c044
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:c40f6edf537c97fe22ac3e0a792c515208a2c044
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:c40f6edf537c97fe22ac3e0a792c515208a2c044
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:c40f6edf537c97fe22ac3e0a792c515208a2c044
        name: clin-proxy-api-variant
