---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-ferload
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-ferload
      containers:
      - image: ferlabcrsj/ferload:ab0a886
        name: clin-ferload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:da872df
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:e5d115be40cd19ea0cbd8d9b8154c0c794bd71d6
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:797b2499fc7d76f42ae2b8b957f6bdc715f2bb0d
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:797b2499fc7d76f42ae2b8b957f6bdc715f2bb0d
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:797b2499fc7d76f42ae2b8b957f6bdc715f2bb0d
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:797b2499fc7d76f42ae2b8b957f6bdc715f2bb0d
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:797b2499fc7d76f42ae2b8b957f6bdc715f2bb0d
        name: clin-proxy-api-variant
