---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-ferload
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-ferload
      containers:
      - image: ferlabcrsj/ferload:1.0.0
        name: clin-ferload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-console
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-console
      containers:
      - image: ferlabcrsj/fhir-console:1.0.0
        name: clin-fhir-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:156d6a3
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:0bbb2ead7d949425e2d0a76890c24a9b0583340a
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:bacccf2581d3e24d03a39aabc6106e44b0613315
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:bacccf2581d3e24d03a39aabc6106e44b0613315
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:bacccf2581d3e24d03a39aabc6106e44b0613315
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:bacccf2581d3e24d03a39aabc6106e44b0613315
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:bacccf2581d3e24d03a39aabc6106e44b0613315
        name: clin-proxy-api-variant
