---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-fhir-server
      containers:
        - image: ferlabcrsj/clin-fhir-server:220bafb
          name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-frontend
      containers:
        - image: ferlabcrsj/clin-frontend:d1898d347797c42472e2eed3589c5d0480b62419
          name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-proxy-api-gene
      containers:
        - image: ferlabcrsj/clin-proxy-api-gene-service:03f644e00d359a7ba48679221c1054da3e23fc62
          name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-proxy-api-hpo
      containers:
        - image: ferlabcrsj/clin-proxy-api-hpo-service:03f644e00d359a7ba48679221c1054da3e23fc62
          name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-proxy-api-meta
      containers:
        - image: ferlabcrsj/clin-proxy-api-meta-service:03f644e00d359a7ba48679221c1054da3e23fc62
          name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-proxy-api-patient
      containers:
        - image: ferlabcrsj/clin-proxy-api-patient-service:03f644e00d359a7ba48679221c1054da3e23fc62
          name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: clin-proxy-api-variant
      containers:
        - image: ferlabcrsj/clin-proxy-api-variant-service:03f644e00d359a7ba48679221c1054da3e23fc62
          name: clin-proxy-api-variant
