---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-ferload
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-ferload
      containers:
      - image: ferlabcrsj/ferload:1.0.0
        name: clin-ferload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-console
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-console
      containers:
      - image: ferlabcrsj/fhir-console:1.0.0
        name: clin-fhir-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-fhir-server
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-fhir-server
      containers:
      - image: ferlabcrsj/clin-fhir-server:dbf2f31
        name: clin-fhir-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-frontend
      containers:
      - image: ferlabcrsj/clin-frontend:0578b2f090126a624c8f198286525eabdc78faf9
        name: clin-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-gene
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-gene
      containers:
      - image: ferlabcrsj/clin-proxy-api-gene-service:adfa308ab6ca205a6e2da1cb20a64b5595457eee
        name: clin-proxy-api-gene
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-hpo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-hpo
      containers:
      - image: ferlabcrsj/clin-proxy-api-hpo-service:adfa308ab6ca205a6e2da1cb20a64b5595457eee
        name: clin-proxy-api-hpo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-meta
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-meta
      containers:
      - image: ferlabcrsj/clin-proxy-api-meta-service:024af15115b86aff2c508e432c92202e37f53ce5
        name: clin-proxy-api-meta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-patient
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-patient
      containers:
      - image: ferlabcrsj/clin-proxy-api-patient-service:adfa308ab6ca205a6e2da1cb20a64b5595457eee
        name: clin-proxy-api-patient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-proxy-api-variant
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clin-proxy-api-variant
      containers:
      - image: ferlabcrsj/clin-proxy-api-variant-service:024af15115b86aff2c508e432c92202e37f53ce5
        name: clin-proxy-api-variant
